FROM nimmis/apache-php7

MAINTAINER david2000tsi@gmail.com

RUN apt-get update && \
    apt-get install -y net-tools iputils-ping php7.0-bcmath \
	php7.0-common php7.0-fpm php7.0-cli php7.0-json \
	php7.0-mysql php7.0-curl php7.0-intl php7.0-mcrypt \
	php-pear php7.0-gd php7.0-zip php7.0-xml php7.0-mbstring \
	php-memcached

WORKDIR /var/www/html
